import random
from enum import Enum
from typing import Literal
from utils.prob_utils import prob_hour_to_prob_sec
from typing import Any
from utils.colors import *
from production_plant import GlobalStateEnum
import globals

class SensorRoleEnum(Enum):
    CRITICAL = 0
    NORMAL = 1
    UNINPORTANT = 2

class SensorTypeEnum(Enum):
    TEMPERATURE = 0

class SensorMessage:
    def __init__(self, sensor_id: int, sensor_type: int, sensor_value: float, timestamp: int):
        self.sensor_id = sensor_id
        self.sensor_type = sensor_type
        self.sensor_value = sensor_value
        self.timestamp = timestamp

class Sensor:    
    def __init__(self,
                 sensor_id: int,
                 sensor_label: str,
                 sensor_type: SensorTypeEnum,
                 role: SensorRoleEnum,  # The relevance of the sensor
                 operating_range: dict[Literal["normal", "degraded", "critical"], tuple[int, int]],
                 mean_value: float, # The mean value of the data generated by the sensor in the beginning
                 sampling_interval: int = 0, # 0 = every millisecond
                ):
        self.sensor_id = sensor_id
        self.sensor_label = sensor_label
        self.sensor_type = sensor_type
        self.role = role
        self.operating_range = operating_range
        if (not self.__operating_range_is_ok()):
            raise Exception("Operating range is not valid")
        self.mean_value = mean_value
        self.standard_deviation = (operating_range['normal'][1] - operating_range['normal'][0]) / 4 # About 96% of the generated data will be inside the normal range
        self.local_state = GlobalStateEnum.NORMAL
        self.sampling_interval = sampling_interval
        self.last_thousand_values: list[float] = []
        self.__initialize_transition_probabilities()
        self.under_maintenance = False
        
    def finish_maintenance(self):
        self.under_maintenance = False

    def __operating_range_is_ok(self):
        """
        Checks if the operating range is valid.

        A valid operating range must have 'normal', 'degraded', and 'critical' ranges.
        Every range must be a range of two values (min, max).
        The 'normal' range must be completely inside the 'degraded' range, and the 'degraded'
        range must be completely inside the 'critical' range.

        Returns:
            bool: True if the operating range is valid, False otherwise.
        """
        if (self.operating_range['normal'][0] >= self.operating_range['normal'][1]):
            return False
        if (self.operating_range['degraded'][0] >= self.operating_range['degraded'][1]):
            return False
        if (self.operating_range['critical'][0] >= self.operating_range['critical'][1]):
            return False
        if (self.operating_range['degraded'][0] >= self.operating_range['normal'][0]):
            return False
        if (self.operating_range['degraded'][1] <= self.operating_range['normal'][1]):
            return False
        if (self.operating_range['critical'][0] >= self.operating_range['degraded'][0]):
            return False
        if (self.operating_range['critical'][1] <= self.operating_range['degraded'][1]):
            return False
        
        return True

    def __initialize_transition_probabilities(self):
        self.original_transition_probabilities = { # Values when the machine is normal
            GlobalStateEnum.NORMAL: {
                GlobalStateEnum.DEGRADED: prob_hour_to_prob_sec(0.01)  # 1% per hour
            },
            GlobalStateEnum.DEGRADED: {
                GlobalStateEnum.CRITICAL: prob_hour_to_prob_sec(0.08), # 8% per hour
                GlobalStateEnum.NORMAL:  prob_hour_to_prob_sec(0.01)  # 1% per hour
            },
            GlobalStateEnum.CRITICAL: {
                GlobalStateEnum.FAILURE: prob_hour_to_prob_sec(0.15), # 15% per hour
                GlobalStateEnum.DEGRADED: prob_hour_to_prob_sec(0.005)  # 0.5% per hour
            }
        }
        self.transition_probabilities = self.original_transition_probabilities
      
    def auto_set_mean_value(self):
        # Calculate the size of the ranges
        normal_range = self.operating_range['normal'][1] - self.operating_range['normal'][0]
        
        if self.local_state == GlobalStateEnum.NORMAL:
            # Change mean value to a random value inside the normal range
            self.mean_value = random.uniform(self.operating_range['normal'][0], self.operating_range['normal'][1])
        elif self.local_state == GlobalStateEnum.DEGRADED:
            if self.old_state == GlobalStateEnum.NORMAL:
                # Change mean value to a random value inside the degraded range but outside the normal range
                self.mean_value = random.uniform(self.operating_range['degraded'][0], self.operating_range['degraded'][1] - normal_range)
                if self.mean_value >= self.operating_range['normal'][0] and self.mean_value <= self.operating_range['normal'][1]:
                    self.mean_value += normal_range
            else:
                critical_to_left = self.mean_value < self.operating_range['normal'][0]
                if (critical_to_left):
                    # Change mean value to the left of the normal range
                    self.mean_value = random.uniform(self.operating_range['degraded'][0], self.operating_range['normal'][0])
                else:
                    # Change mean value to the right of the normal range
                    self.mean_value = random.uniform(self.operating_range['normal'][1], self.operating_range['degraded'][1])
        elif self.local_state == GlobalStateEnum.CRITICAL:
            # Verify if the mean value is more to the left or to the right of the degraded range
            degraded_to_left = self.mean_value < self.operating_range['normal'][0]
            if (degraded_to_left):
                # Change mean value to the left of the degraded range
                self.mean_value = random.uniform(self.operating_range['critical'][0], self.operating_range['degraded'][0])
            else:
                # Change mean value to the right of the degraded range
                self.mean_value = random.uniform(self.operating_range['degraded'][1], self.operating_range['critical'][1])
        elif self.local_state == GlobalStateEnum.FAILURE:
            # Verify if the mean value is more to the left or to the right of the critical range
            critical_to_left = self.mean_value < self.operating_range['normal'][0]
            if (critical_to_left):
                # Change mean value to the left of the critical range using a mirrored to left normal distribution with the mean value on the border of the critical range
                self.mean_value = random.normalvariate(self.operating_range['critical'][0], self.standard_deviation)
                if self.mean_value >= self.operating_range['critical'][0]:
                    self.mean_value = self.operating_range['critical'][0] + (self.operating_range['critical'][0] - self.mean_value)
            else:
                # Change mean value to the right of the critical range using a mirrored to right normal distribution with the mean value on the border of the critical range
                self.mean_value = random.normalvariate(self.operating_range['critical'][1], self.standard_deviation)
                if self.mean_value <= self.operating_range['critical'][1]:
                    self.mean_value = self.operating_range['critical'][1] - (self.mean_value - self.operating_range['critical'][1])
                
            
        
    def update_state_by_probabilities(self):
        """
        Updates the state of the sensor based on the transition probabilities.

        The method generates a random value between 0 and 1, and then iterates over the transition probabilities
        associated with the current state of the sensor. If the random value is less than the probability of a
        transition to a certain state, the sensor's state is updated to that state and the mean value is
        updated accordingly.

        If the sensor's state is updated, the method also sets the sp flag of the actuator to True and prints a
        message indicating the update.
        """
        rand_value = random.uniform(0, 1)
        
        possibly_states = self.transition_probabilities[self.local_state] if self.local_state != GlobalStateEnum.FAILURE else {}
        
        prob_sum = 0
        
        for state, probability in possibly_states.items():
            if rand_value < probability + prob_sum and probability >= prob_sum:
                self.old_state = self.local_state
                self.local_state = state
                self.auto_set_mean_value()
                self.last_update_by_prob = (globals.time, self.old_state, self.local_state)
                print(
                    f"{MAGENTA}Time: {globals.time / 60000} minutes, Sensor {self.sensor_id}({self.get_true_role()}) updated state from {self.old_state} to {self.local_state} and now has a mean value of {self.mean_value}{RESET}")
                break
    
    def get_last_update_by_prob(self):
        if ('last_update_by_prob' in self.__dict__):
            return self.last_update_by_prob
        else:
            return None
        
    def get_old_state(self):
        if ('old_state' in self.__dict__):
            return self.old_state
        else:
            return None

    def upkeep(self):
        """
        The upkeep method is called when the sensor is not in the NORMAL state.

        If the sensor is in the DEGRADED state, it is updated to the NORMAL state.

        If the sensor is in the CRITICAL state, it is updated to the DEGRADED state.

        The method prints a message indicating the update of the sensor's state.
        """
        self.old_state = self.local_state
        self.local_state = GlobalStateEnum.NORMAL
        self.auto_set_mean_value()
        self.last_upkeep = (globals.time, self.old_state, self.local_state)
        
    def get_last_upkeep(self):
        if ('last_upkeep' in self.__dict__):
            return self.last_upkeep
        else:
            return None
        
    def get_true_role(self):
        return self.role

    def observe(self, state):
        pass

    def read_value(self):
        """
        Returns a random value from a normal distribution with mean
        self.mean_value and standard deviation self.standard_deviation.
        """
        self.last_value = random.normalvariate(
            self.mean_value, self.standard_deviation)  # Normal distribution
        self.last_thousand_values.append(self.last_value)
        self.last_thousand_values = self.last_thousand_values[-2000:] 
        return self.last_value  

    def get_last_value(self):
        if ('last_value' in self.__dict__):
            return self.last_value
        else:
            return None
        
    def get_last_thousand_values(self):
        if ('last_thousand_values' in self.__dict__):
            return self.last_thousand_values
        else:
            return None

    def send_data(self) -> SensorMessage | None:
        if (globals.time % self.sampling_interval != 0): 
            return None
        
        message=SensorMessage(
            sensor_id= self.sensor_id,
            sensor_type= self.sensor_type.value,
            sensor_value= self.read_value(),
            timestamp= globals.time
        )
        self.last_message = message
        return message

    def get_last_message(self):
        if ('last_message' in self.__dict__):
            return self.last_message
        else:
            return None
    
    