import random
from enum import Enum
from typing import Literal
from globals import Globals
import time
from prob_utils import prob_hour_to_prob_min
from typing import Any

class SensorStateEnum(Enum):
    NORMAL = 0
    DEGRADED = 1
    CRITICAL = 2
    FAILURE = 3

class SensorRoleEnum(Enum):
    CRITICAL = 0
    NORMAL = 1
    UNINPORTANT = 2

class SensorTypeEnum(Enum):
    TEMPERATURE = 0
    HUMIDITY = 1
    PRESSURE = 2
    LIGHT = 3
    MOISTURE = 4
    AIR_QUALITY = 5
    

RESET = "\033[0m"
VERMELHO = "\033[31m"
VERDE = "\033[32m"
AMARELO = "\033[33m"
AZUL = "\033[34m"
MAGENTA = "\033[35m"
CIANO = "\033[36m"

class Sensor:
    id = 0
    
    def __init__(self,
                 sensor_id: int,
                 sensor_type: SensorTypeEnum,
                 role: SensorRoleEnum,  # The relevance of the sensor
                 operating_range: dict[Literal["normal", "degraded", "critical"], tuple[int, int]],
                 mean_value: float, # The mean value of the data generated by the sensor in the beginning
                 sampling_interval: int = 0, # 0 = every millisecond
                ):
        self.sensor_id = sensor_id
        self.sensor_type = sensor_type
        self.role = role
        self.operating_range = operating_range
        if (not self.__operating_range_is_ok()):
            raise Exception("Operating range is not valid")
        self.mean_value = mean_value
        self.standard_deviation = (operating_range['normal'][1] - operating_range['normal'][0]) / 2 # About 96% of the generated data will be inside the normal range
        self.local_state = SensorStateEnum.NORMAL
        self.sampling_interval = sampling_interval
        self.__initialize_transition_probabilities()

    def __operating_range_is_ok(self):
        """
        Checks if the operating range is valid.

        A valid operating range must have 'normal', 'degraded', and 'critical' ranges.
        Every range must be a range of two values (min, max).
        The 'normal' range must be completely inside the 'degraded' range, and the 'degraded'
        range must be completely inside the 'critical' range.

        Returns:
            bool: True if the operating range is valid, False otherwise.
        """
        if (self.operating_range['normal'][0] >= self.operating_range['normal'][1]):
            return False
        if (self.operating_range['degraded'][0] >= self.operating_range['degraded'][1]):
            return False
        if (self.operating_range['critical'][0] >= self.operating_range['critical'][1]):
            return False
        if (self.operating_range['degraded'][0] >= self.operating_range['normal'][0]):
            return False
        if (self.operating_range['degraded'][1] <= self.operating_range['normal'][1]):
            return False
        if (self.operating_range['critical'][0] >= self.operating_range['degraded'][0]):
            return False
        if (self.operating_range['critical'][1] <= self.operating_range['degraded'][1]):
            return False
        
        return True

    def __initialize_transition_probabilities(self):
        self.original_transition_probabilities = { # Values when the machine is normal
            SensorStateEnum.NORMAL: {
                SensorStateEnum.DEGRADED: random.uniform(prob_hour_to_prob_min(0.008), prob_hour_to_prob_min(.012)) # 0.8% to 1.2% per hour
            },
            SensorStateEnum.DEGRADED: {
                SensorStateEnum.CRITICAL: random.uniform(prob_hour_to_prob_min(0.08), prob_hour_to_prob_min(0.16)), # 8% to 16% per hour
                SensorStateEnum.NORMAL: random.uniform(prob_hour_to_prob_min(0.001), prob_hour_to_prob_min(0.002)) # 0.1% to 0.2% per hour
            },
            SensorStateEnum.CRITICAL: {
                SensorStateEnum.FAILURE: random.uniform(prob_hour_to_prob_min(0.15), prob_hour_to_prob_min(0.4)), # 15% to 40% per hour
                SensorStateEnum.DEGRADED: random.uniform(prob_hour_to_prob_min(0.001), prob_hour_to_prob_min(0.002)) # 1% to 2% per hour
            }
        }
        self.transition_probabilities = self.original_transition_probabilities
        print(f'Sensor {self.sensor_id} initialized with transition probabilities:')
        print(f'NORMAL->DEGRADED: {self.transition_probabilities[SensorStateEnum.NORMAL][SensorStateEnum.DEGRADED]}')
        print(f'DEGRADED->CRITICAL: {self.transition_probabilities[SensorStateEnum.DEGRADED][SensorStateEnum.CRITICAL]}')
        print(f'CRITICAL->FAILURE: {self.transition_probabilities[SensorStateEnum.CRITICAL][SensorStateEnum.FAILURE]}')
        print(f'CRITICAL->DEGRADED: {self.transition_probabilities[SensorStateEnum.CRITICAL][SensorStateEnum.DEGRADED]}')
        print(f'DEGRADED->NORMAL: {self.transition_probabilities[SensorStateEnum.DEGRADED][SensorStateEnum.NORMAL]}')

    # Not used yet
    # def adjust_probabilities_by_time_passing(self):
    #     if (self.local_state == SensorStateEnum.NORMAL):
    #         self.transition_probabilities[SensorStateEnum.NORMAL][SensorStateEnum.DEGRADED] += 0.0001 # increase by 0.01%
        
    #     if (self.local_state == SensorStateEnum.DEGRADED):
    #         self.transition_probabilities[SensorStateEnum.DEGRADED][SensorStateEnum.CRITICAL] += 0.0002 # increase by 0.02%
    #         self.transition_probabilities[SensorStateEnum.DEGRADED][SensorStateEnum.NORMAL] -= 0.0001 # decrease by 0.01%
        
    #     if (self.local_state == SensorStateEnum.CRITICAL):
    #         self.transition_probabilities[SensorStateEnum.CRITICAL][SensorStateEnum.FAILURE] += 0.0004 # increase by 0.04%
    #         self.transition_probabilities[SensorStateEnum.CRITICAL][SensorStateEnum.DEGRADED] -= 0.0002 # decrease by 0.02%
        
    def auto_set_mean_value(self):
        # Calculate the size of the ranges
        normal_range = self.operating_range['normal'][1] - self.operating_range['normal'][0]
        critical_range = self.operating_range['critical'][1] - self.operating_range['critical'][0]
        
        if self.local_state == SensorStateEnum.NORMAL:
            # Change mean value to a random value inside the normal range
            self.mean_value = random.uniform(self.operating_range['normal'][0], self.operating_range['normal'][1])
        elif self.local_state == SensorStateEnum.DEGRADED:
            # Change mean value to a random value inside the degraded range but outside the normal range
            self.mean_value = random.uniform(self.operating_range['degraded'][0], self.operating_range['degraded'][1] - normal_range)
            if self.mean_value >= self.operating_range['normal'][0] and self.mean_value <= self.operating_range['normal'][1]:
                self.mean_value += normal_range
        elif self.local_state == SensorStateEnum.CRITICAL:
            # Verify if the mean value is more to the left or to the right of the degraded range
            degraded_to_left = self.mean_value < self.operating_range['normal'][0]
            if (degraded_to_left):
                # Change mean value to the left of the degraded range
                self.mean_value = random.uniform(self.operating_range['critical'][0], self.operating_range['degraded'][0])
            else:
                # Change mean value to the right of the degraded range
                self.mean_value = random.uniform(self.operating_range['degraded'][1], self.operating_range['critical'][1])
        elif self.local_state == SensorStateEnum.FAILURE:
            # Verify if the mean value is more to the left or to the right of the critical range
            critical_to_left = self.mean_value < self.operating_range['normal'][0]
            if (critical_to_left):
                # Change mean value to the left of the critical range using a mirrored to left normal distribution with the mean value on the border of the critical range
                self.mean_value = random.normalvariate(self.operating_range['critical'][0], critical_range)
                if self.mean_value >= self.operating_range['critical'][0]:
                    self.mean_value = self.operating_range['critical'][0] + (self.operating_range['critical'][0] - self.mean_value)
            else:
                # Change mean value to the right of the critical range using a mirrored to right normal distribution with the mean value on the border of the critical range
                self.mean_value = random.normalvariate(self.operating_range['critical'][1], critical_range)
                if self.mean_value <= self.operating_range['critical'][1]:
                    self.mean_value = self.operating_range['critical'][1] - (self.mean_value - self.operating_range['critical'][1])
                
            
        
    def update_state_by_probabilities(self):
        """
        Updates the state of the sensor based on the transition probabilities.

        The method generates a random value between 0 and 1, and then iterates over the transition probabilities
        associated with the current state of the sensor. If the random value is less than the probability of a
        transition to a certain state, the sensor's state is updated to that state and the mean value is
        updated accordingly.

        If the sensor's state is updated, the method also sets the sp flag of the actuator to True and prints a
        message indicating the update.
        """
        rand_value = random.uniform(0, 1)
        
        possibly_states = self.transition_probabilities[self.local_state] if self.local_state != SensorStateEnum.FAILURE else {}
        
        prob_sum = 0
        
        for state, probability in possibly_states.items():
            if rand_value < probability + prob_sum and probability >= prob_sum:
                old_state = self.local_state
                self.local_state = state
                self.auto_set_mean_value()
                print(
                    f"{MAGENTA}Time: {Globals.time / 60000} minutes, Sensor {self.sensor_id}({self.get_true_role()}) updated state from {old_state} to {self.local_state} and now has a mean value of {self.mean_value}{RESET}")
                Globals.actuator.sp = True
                # print(f'NORMAL->DEGRADED: {self.transition_probabilities[SensorStateEnum.NORMAL][SensorStateEnum.DEGRADED]}')
                # print(f'DEGRADED->CRITICAL: {self.transition_probabilities[SensorStateEnum.DEGRADED][SensorStateEnum.CRITICAL]}')
                # print(f'DEGRADED->NORMAL: {self.transition_probabilities[SensorStateEnum.DEGRADED][SensorStateEnum.NORMAL]}')
                # print(f'CRITICAL->FAILURE: {self.transition_probabilities[SensorStateEnum.CRITICAL][SensorStateEnum.FAILURE]}')
                # print(f'CRITICAL->DEGRADED: {self.transition_probabilities[SensorStateEnum.CRITICAL][SensorStateEnum.DEGRADED]}')
                break

    def upkeep(self):
        """
        The upkeep method is called when the sensor is not in the NORMAL state.

        If the sensor is in the DEGRADED state, it is updated to the NORMAL state.

        If the sensor is in the CRITICAL state, it is updated to the DEGRADED state.

        The method prints a message indicating the update of the sensor's state.
        """
        if (self.local_state == SensorStateEnum.DEGRADED):
            self.local_state = SensorStateEnum.NORMAL
            print(f"{VERDE}Time: {Globals.time / 60000} minutes, Sensor {self.sensor_id} ({self.get_true_role()}) upkept from DEGRADED to NORMAL{RESET}")
        elif (self.local_state == SensorStateEnum.CRITICAL):
            self.local_state = SensorStateEnum.DEGRADED
            print(
                f"{VERDE}Time: {Globals.time / 60000} minutes, Sensor {self.sensor_id} ({self.get_true_role()}) upkept from from CRITICAL to DEGRADED{RESET}")

    def get_true_role(self):
        return self.role

    def observe(self, state):
        pass

    def read_value(self):
        """
        Returns a random value from a normal distribution with mean
        self.mean_value and standard deviation self.standard_deviation.
        """
        return random.normalvariate(self.mean_value, self.standard_deviation)  # Normal distribution

    def send_data(self) -> dict[str, Any] | None:
        if (Globals.time % self.sampling_interval != 0): 
            return None
        
        message={
            'sensor_id': self.sensor_id,
            'sensor_type': self.sensor_type.value,
            'sensor_value': self.read_value(),
            'timestamp': Globals.time
        }
        return message

    @classmethod
    def next_id(cls):
        cls.id += 1
        return cls.id